node C:\JD\Super_JD\jd_joy_feedPets.js
node C:\JD\Super_JD\jd_speed.js
node C:\JD\Super_JD\jd_daily_egg.js
node C:\JD\Super_JD\jd_moneyTree.js
node C:\JD\Super_JD\jd_superMarket.js
node C:\JD\Super_JD\jd_bookshop.js
node C:\JD\Super_JD\jd_dreamFactory.js
node C:\JD\Super_JD\jd_jdfactory.js
node C:\JD\Super_JD\jd_plantBean.js
node C:\JD\Super_JD\jd_pet.js
